name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

env:
  DUNE_PROFILE: release
  OCAMLRUNPARAM: b

permissions:
  contents: write

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

defaults:
  run:
    shell: bash -xeuo pipefail {0}

jobs:
  build:
    name: Build and test

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        ocaml-compiler:
          - 4.14.2
          - 5.4.0

    steps:
      - uses: actions/checkout@v4

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Install dependencies
        run: make install

      - name: Build
        run: make build

      - name: Check formatting
        run: make format-check

      - name: Run tests
        run: make test

      - name: Install dune-release
        if: startsWith(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-latest' && matrix.ocaml-compiler == '5.4.0'
        run: opam install dune-release -y

      - name: Release
        uses: davesnx/dune-release-action@v0.4.0
        if: startsWith(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-latest' && matrix.ocaml-compiler == '5.4.0'
        with:
          packages: react-rules-of-hooks-ppx
          changelog: ./CHANGES.md
          github-token: ${{ secrets.GH_TOKEN }}
